// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_Screen1;
lv_obj_t * ui_lblSdCard;
lv_obj_t * ui_lblPath;
lv_obj_t * ui_btnTest;
lv_obj_t * ui_Label2;
lv_obj_t * ui_txaFiles;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSdCard = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblSdCard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSdCard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSdCard, 128);
    lv_obj_set_y(ui_lblSdCard, -142);
    lv_obj_set_align(ui_lblSdCard, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSdCard, "SD Card");

    ui_lblPath = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblPath, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPath, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPath, 29);
    lv_obj_set_y(ui_lblPath, -121);
    lv_obj_set_align(ui_lblPath, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPath, "Path");

    ui_btnTest = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnTest, 100);
    lv_obj_set_height(ui_btnTest, 50);
    lv_obj_set_x(ui_btnTest, -143);
    lv_obj_set_y(ui_btnTest, -88);
    lv_obj_set_align(ui_btnTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -142);
    lv_obj_set_y(ui_Label2, -86);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_txaFiles = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_txaFiles, 231);
    lv_obj_set_height(ui_txaFiles, 225);
    lv_obj_set_x(ui_txaFiles, 118);
    lv_obj_set_y(ui_txaFiles, 6);
    lv_obj_set_align(ui_txaFiles, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_txaFiles, LV_SCROLLBAR_MODE_ON);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
