// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_Screen1;
lv_obj_t * ui_lblSdCard;
lv_obj_t * ui_lblPath;
void ui_event_btnSample(lv_event_t * e);
lv_obj_t * ui_btnSample;
lv_obj_t * ui_Label2;
lv_obj_t * ui_txaFiles;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_lblTemp;
lv_obj_t * ui_lblPressure;
lv_obj_t * ui_Label4;
void ui_event_btnLs(lv_event_t * e);
lv_obj_t * ui_btnLs;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
void ui_event_sldBacklight(lv_event_t * e);
lv_obj_t * ui_sldBacklight;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnSample(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnSampleClicked(e);
    }
}
void ui_event_btnLs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnLsClicked(e);
    }
}
void ui_event_sldBacklight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SldBacklightChanged(e);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSdCard = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblSdCard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSdCard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSdCard, 128);
    lv_obj_set_y(ui_lblSdCard, -142);
    lv_obj_set_align(ui_lblSdCard, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSdCard, "SD Card");

    ui_lblPath = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblPath, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPath, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPath, 247);
    lv_obj_set_y(ui_lblPath, -124);
    lv_obj_set_align(ui_lblPath, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblPath, "Path");

    ui_btnSample = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnSample, 92);
    lv_obj_set_height(ui_btnSample, 37);
    lv_obj_set_x(ui_btnSample, -161);
    lv_obj_set_y(ui_btnSample, 9);
    lv_obj_set_align(ui_btnSample, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSample, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSample, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_btnSample);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Sample");

    ui_txaFiles = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_txaFiles, 231);
    lv_obj_set_height(ui_txaFiles, 214);
    lv_obj_set_x(ui_txaFiles, 117);
    lv_obj_set_y(ui_txaFiles, -3);
    lv_obj_set_align(ui_txaFiles, LV_ALIGN_CENTER);

    lv_obj_set_style_text_color(ui_txaFiles, lv_color_hex(0x808080), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txaFiles, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txaFiles, LV_TEXT_ALIGN_LEFT, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 26);
    lv_obj_set_y(ui_Label3, 49);
    lv_label_set_text(ui_Label3, "Temperature");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 26);
    lv_obj_set_y(ui_Label1, 96);
    lv_label_set_text(ui_Label1, "Pressure");

    ui_lblTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblTemp, 200);
    lv_obj_set_height(ui_lblTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemp, 35);
    lv_obj_set_y(ui_lblTemp, 73);
    lv_label_set_text(ui_lblTemp, "");
    lv_obj_set_style_border_color(ui_lblTemp, lv_color_hex(0x640000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPressure = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblPressure, 200);
    lv_obj_set_height(ui_lblPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPressure, 35);
    lv_obj_set_y(ui_lblPressure, 119);
    lv_label_set_text(ui_lblPressure, "");
    lv_obj_set_style_border_color(ui_lblPressure, lv_color_hex(0x640000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblPressure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 11);
    lv_obj_set_y(ui_Label4, 26);
    lv_label_set_text(ui_Label4, "BMP280");

    ui_btnLs = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnLs, 92);
    lv_obj_set_height(ui_btnLs, 36);
    lv_obj_set_x(ui_btnLs, 58);
    lv_obj_set_y(ui_btnLs, 132);
    lv_obj_set_align(ui_btnLs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnLs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnLs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_btnLs);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "List Files");

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 26);
    lv_obj_set_y(ui_Label6, 209);
    lv_label_set_text(ui_Label6, "Backlight");

    ui_sldBacklight = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_sldBacklight, 10, 100);
    lv_obj_set_width(ui_sldBacklight, 188);
    lv_obj_set_height(ui_sldBacklight, 10);
    lv_obj_set_x(ui_sldBacklight, 38);
    lv_obj_set_y(ui_sldBacklight, 238);

    lv_obj_add_event_cb(ui_btnSample, ui_event_btnSample, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLs, ui_event_btnLs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldBacklight, ui_event_sldBacklight, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
