// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_lblSdCard;
extern lv_obj_t * ui_lblPath;
void ui_event_btnSample(lv_event_t * e);
extern lv_obj_t * ui_btnSample;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_txaFiles;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_lblTemp;
extern lv_obj_t * ui_lblPressure;
extern lv_obj_t * ui_Label4;
void ui_event_btnLs(lv_event_t * e);
extern lv_obj_t * ui_btnLs;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
